import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Button } from "react-bootstrap";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    console.log("メール送信");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mt-5">
        <h2 className="mb-3">Gmail App using Next.js</h2>
        <form
          onSubmit={(e: React.FormEvent<HTMLFormElement>) => handleSubmit(e)}>
          <div className="mb-3">
            <label htmlFor="Name" className="form-label">
              Name
            </label>
            <input type="text" className="form-control" id="name" required />
          </div>
          <div className="mb-3">
            <label htmlFor="Email" className="form-label">
              Email
            </label>
            <input type="text" className="form-control" id="email" required />
          </div>
          <div className="mb-3">
            <label htmlFor="Name" className="form-label">
              Message
            </label>
            <textarea
              name="message"
              className="form-control"
              id="message"></textarea>
          </div>
          <button type="submit" className="btn btn-danger">
            送信
          </button>
        </form>
      </div>
    </>
  );
}
